services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: risotto-frontend:latest
    container_name: frontend-app
    ports:
      - "5173:5173"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    external: true
